import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PreferencesProvider } from "@/context/PreferencesContext";
import { VideoLinkProvider } from "@/context/VideoLinkContext";

import CameraPermission from "@/components/CameraPermission";
import CameraPreview from "@/components/CameraPreview";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PreferencesProvider>
          <VideoLinkProvider>
            {children}
            <CameraPermission />
            <CameraPreview />
          </VideoLinkProvider>
        </PreferencesProvider>
      </body>
    </html>
  );
}
