import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PreferencesProvider } from "@/context/PreferencesContext";
import { DataProvider } from "@/context/DataContext";
import { VideoProvider } from "@/context/VideoContext";

import CameraPermission from "@/components/CameraPermission";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DataProvider>
          <PreferencesProvider>
            <VideoProvider>
              {children}
              <CameraPermission />
            </VideoProvider>
          </PreferencesProvider>
        </DataProvider>
      </body>
    </html>
  );
}
